version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t wataken44/ubuntu-latest-sshd .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push wataken44/ubuntu-latest-sshd
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "31 14 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
